### ISSUE TITLE
Document userNameKey for AWS Cognito

### ISSUE THREAD

**Issue by owu-1** [deployKF/website#112]
Add ```userNameKey: cognito:username``` to the AWS Cognito provider example [here](https://www.deploykf.org/guides/platform/deploykf-authentication/#provider-examples) otherwise you cannot login. Here is someone's explanation https://github.com/argoproj/argo-cd/discussions/12185#discussioncomment-4799460.

Also maybe remove the ```offline_access``` scope? I don't know what that is and it errors with "invalid scope" when I add it.

**Comment by thesuperzapper** [comment]
@owu-1 thanks for the catch on the `userNameKey`.

I think it must be another non-standard Cognito thin that `offline_access` is not recognised (in most OIDC providers, this tells the provider to issue a `refresh_token`).

Can you tell me if you are being forced to re-log every 60 minuets (because that would indicate that the refresh token is not working)?

**Comment by owu-1** [comment]
After 60 minutes it doesn't ask me to login in again

**Comment by thesuperzapper** [comment]
I have updated the website: https://www.deploykf.org/guides/platform/deploykf-authentication/#aws-cognito

Thanks!
